services:
  network-api:
    build: .
    container_name: network-api
    ports:
      - "8088:8000"
    volumes:
      - ./app:/app/app        # Volume pour recharger le code sans rebuild
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload